"""
FormFlow PDF Export Service
============================
Generates a clean, professional Application Summary PDF using ReportLab.
This is a clearly labeled APPLICATION SUMMARY, not a pretend official document.
"""
from __future__ import annotations
import io
import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

try:
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm, mm
    from reportlab.platypus import (
        BaseDocTemplate, Frame, HRFlowable, Image, PageBreak,
        PageTemplate, Paragraph, Spacer, Table, TableStyle
    )
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    logger.warning("ReportLab not available. PDF export will use text fallback.")


# ---------------------------------------------------------------------------
# Colours
# ---------------------------------------------------------------------------
PRIMARY = colors.HexColor("#4F46E5")       # Indigo
PRIMARY_LIGHT = colors.HexColor("#EEF2FF")
SUCCESS = colors.HexColor("#059669")
WARNING_COLOR = colors.HexColor("#D97706")
ERROR_COLOR = colors.HexColor("#DC2626")
MUTED = colors.HexColor("#6B7280")
TEXT = colors.HexColor("#111827")
BORDER = colors.HexColor("#E5E7EB")
SECTION_BG = colors.HexColor("#F9FAFB")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _format_value(value: Any, field_type: str = "text") -> str:
    """Format a field value for display."""
    if value is None or value == "":
        return "—"
    if isinstance(value, bool):
        return "✓ Accepted" if value else "✗ Not accepted"
    s = str(value).strip()
    if field_type == "currency" and s and s.replace(",", "").replace(".", "").isdigit():
        try:
            num = float(s.replace(",", ""))
            return f"₹{num:,.0f}"
        except Exception:
            pass
    return s if s else "—"


def _issue_color(severity: str) -> Any:
    if severity == "error":
        return ERROR_COLOR
    if severity == "warning":
        return WARNING_COLOR
    return colors.HexColor("#2563EB")


def _issue_symbol(severity: str) -> str:
    if severity == "error":
        return "✗"
    if severity == "warning":
        return "⚠"
    return "ℹ"


# ---------------------------------------------------------------------------
# PDF Generator
# ---------------------------------------------------------------------------

def generate_export_pdf(
    form_document: dict,
    values: Dict[str, Any],
    issues: List[dict],
    uploaded_documents: Optional[List[str]] = None,
) -> bytes:
    """
    Generate the Application Summary PDF.
    Returns raw bytes of the PDF.
    """
    if not REPORTLAB_AVAILABLE:
        return _generate_text_fallback(form_document, values, issues)

    buffer = io.BytesIO()

    doc = BaseDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2 * cm,
        title=f"FormFlow — {form_document.get('title', 'Application')} Summary",
        author="FormFlow",
    )

    # Page template with header/footer
    frame = Frame(
        doc.leftMargin, doc.bottomMargin,
        doc.width, doc.height,
        id="main", showBoundary=0,
    )

    def on_page(canvas, doc):
        canvas.saveState()
        # Header bar
        canvas.setFillColor(PRIMARY)
        canvas.rect(0, A4[1] - 1.2 * cm, A4[0], 1.2 * cm, fill=1, stroke=0)
        canvas.setFillColor(colors.white)
        canvas.setFont("Helvetica-Bold", 10)
        canvas.drawString(2 * cm, A4[1] - 0.85 * cm, "FORMFLOW")
        canvas.setFont("Helvetica", 9)
        canvas.drawRightString(A4[0] - 2 * cm, A4[1] - 0.85 * cm, "APPLICATION SUMMARY")

        # Footer
        canvas.setFillColor(MUTED)
        canvas.setFont("Helvetica", 7.5)
        canvas.drawString(2 * cm, 1.2 * cm, f"Generated by FormFlow on {datetime.now().strftime('%d %B %Y, %H:%M')}")
        canvas.drawRightString(A4[0] - 2 * cm, 1.2 * cm, f"Page {doc.page}")

        # Footer divider
        canvas.setStrokeColor(BORDER)
        canvas.line(2 * cm, 1.5 * cm, A4[0] - 2 * cm, 1.5 * cm)
        canvas.restoreState()

    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=on_page)])

    # Styles
    styles = getSampleStyleSheet()
    style_normal = ParagraphStyle(
        "Normal", parent=styles["Normal"],
        fontSize=9, textColor=TEXT, leading=14,
    )
    style_title = ParagraphStyle(
        "Title", parent=styles["Heading1"],
        fontSize=20, textColor=PRIMARY, spaceAfter=4,
        fontName="Helvetica-Bold", alignment=TA_LEFT,
    )
    style_subtitle = ParagraphStyle(
        "Subtitle", parent=styles["Normal"],
        fontSize=10, textColor=MUTED, spaceAfter=12,
    )
    style_section_title = ParagraphStyle(
        "SectionTitle", parent=styles["Normal"],
        fontSize=12, textColor=PRIMARY, fontName="Helvetica-Bold",
        spaceBefore=6, spaceAfter=4,
    )
    style_label = ParagraphStyle(
        "Label", parent=styles["Normal"],
        fontSize=8, textColor=MUTED, fontName="Helvetica",
    )
    style_value = ParagraphStyle(
        "Value", parent=styles["Normal"],
        fontSize=9.5, textColor=TEXT, fontName="Helvetica",
    )
    style_disclaimer = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"],
        fontSize=8, textColor=MUTED, leading=12, borderPadding=8,
    )

    story = []
    story.append(Spacer(1, 0.5 * cm))

    # ── Document title
    title = form_document.get("title", "Application Form")
    story.append(Paragraph(title, style_title))
    story.append(Paragraph(
        form_document.get("description", ""),
        style_subtitle,
    ))

    # ── Disclaimer banner
    disclaimer_data = [[Paragraph(
        "⚠  IMPORTANT: This is a FormFlow Application Summary, not an official form. "
        "This document is generated for reference only. Always submit using the official "
        "channel specified by the issuing authority.",
        style_disclaimer,
    )]]
    disclaimer_table = Table(disclaimer_data, colWidths=[doc.width])
    disclaimer_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FFFBEB")),
        ("BOX", (0, 0), (-1, -1), 0.5, WARNING_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(disclaimer_table)
    story.append(Spacer(1, 0.4 * cm))

    # ── Meta info row
    meta = form_document.get("metadata", {})
    generated_on = datetime.now().strftime("%d %B %Y")
    meta_data = [
        ["Document:", meta.get("original_filename", "N/A")],
        ["Generated:", generated_on],
        ["Mode:", "Demo Mode" if meta.get("is_demo") else "Real Document"],
    ]
    meta_table = Table(meta_data, colWidths=[3 * cm, doc.width - 3 * cm])
    meta_table.setStyle(TableStyle([
        ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 8),
        ("FONT", (1, 0), (1, -1), "Helvetica", 8),
        ("TEXTCOLOR", (0, 0), (-1, -1), MUTED),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(meta_table)
    story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=12))

    # ── Sections and fields
    sections = form_document.get("sections", [])
    sections_sorted = sorted(sections, key=lambda s: s.get("order", 0))

    for section in sections_sorted:
        section_title = f"{section.get('icon', '📄')}  {section.get('title', 'Section')}"
        story.append(Paragraph(section_title, style_section_title))

        desc = section.get("description")
        if desc:
            story.append(Paragraph(desc, style_subtitle))

        fields = section.get("fields", [])
        if not fields:
            story.append(Paragraph("No fields in this section.", style_normal))
            story.append(Spacer(1, 0.3 * cm))
            continue

        # Build two-column table for fields
        rows = []
        for i in range(0, len(fields), 2):
            row = []
            for j in range(2):
                if i + j < len(fields):
                    field = fields[i + j]
                    ftype = field.get("type", "text")
                    val = values.get(field.get("id", ""), None)
                    label_p = Paragraph(field.get("label", ""), style_label)
                    value_p = Paragraph(_format_value(val, ftype), style_value)
                    cell = [label_p, value_p]
                    row.append(cell)
                else:
                    row.append("")
            rows.append(row)

        col_w = doc.width / 2 - 0.5 * cm
        field_table = Table(rows, colWidths=[col_w, col_w])
        field_table.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [SECTION_BG, colors.white]),
            ("BOX", (0, 0), (-1, -1), 0.5, BORDER),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, BORDER),
        ]))
        story.append(field_table)
        story.append(Spacer(1, 0.4 * cm))

    # ── Supporting Documents
    story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceBefore=8, spaceAfter=8))
    story.append(Paragraph("📁  Supporting Documents", style_section_title))

    required_docs = form_document.get("required_documents", [])
    uploaded_ids = uploaded_documents or []
    doc_rows = [
        [
            Paragraph("Document", style_label),
            Paragraph("Required", style_label),
            Paragraph("Status", style_label),
        ]
    ]
    for req_doc in required_docs:
        uploaded = req_doc.get("id") in uploaded_ids
        status_text = "✓ Uploaded" if uploaded else "✗ Not uploaded"
        status_color = SUCCESS if uploaded else MUTED
        doc_rows.append([
            Paragraph(req_doc.get("name", ""), style_value),
            Paragraph("Yes" if req_doc.get("required") else "No", style_normal),
            Paragraph(f'<font color="{"#059669" if uploaded else "#6B7280"}">{status_text}</font>', style_normal),
        ])

    if doc_rows:
        doc_table = Table(doc_rows, colWidths=[doc.width * 0.5, doc.width * 0.2, doc.width * 0.3])
        doc_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_LIGHT),
            ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 8),
            ("TEXTCOLOR", (0, 0), (-1, 0), PRIMARY),
            ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("BOX", (0, 0), (-1, -1), 0.5, BORDER),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, BORDER),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SECTION_BG]),
        ]))
        story.append(doc_table)

    story.append(Spacer(1, 0.4 * cm))

    # ── Validation Issues
    if issues:
        story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceBefore=8, spaceAfter=8))
        story.append(Paragraph("⚠  Validation Issues", style_section_title))

        for issue in issues:
            severity = issue.get("severity", "info")
            sym = _issue_symbol(severity)
            ic = _issue_color(severity)

            issue_data = [[
                Paragraph(
                    f'<font color="#{ic.hexval()[2:]}">{sym}  <b>{issue.get("title", "Issue")}</b></font>',
                    style_normal,
                ),
                Paragraph(issue.get("severity", "info").upper(), style_label),
            ]]
            desc = issue.get("description", "")
            action = issue.get("suggested_action", "")
            if desc:
                issue_data.append([Paragraph(desc, style_normal), ""])
            if action:
                issue_data.append([
                    Paragraph(f"<i>Suggested: {action}</i>", style_label), ""
                ])

            issue_table = Table(
                issue_data,
                colWidths=[doc.width * 0.85, doc.width * 0.15],
            )
            bg = colors.HexColor("#FEF2F2") if severity == "error" else colors.HexColor("#FFFBEB")
            issue_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), bg),
                ("BOX", (0, 0), (-1, -1), 0.5, ic),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("SPAN", (0, 1), (1, 1)),
                ("SPAN", (0, 2), (1, 2)),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("FONT", (1, 0), (1, 0), "Helvetica-Bold", 7),
                ("TEXTCOLOR", (1, 0), (1, 0), ic),
                ("ALIGN", (1, 0), (1, 0), "RIGHT"),
            ]))
            story.append(issue_table)
            story.append(Spacer(1, 0.2 * cm))
    else:
        story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceBefore=8, spaceAfter=8))
        story.append(Paragraph("✓  No Validation Issues Found", style_section_title))
        story.append(Paragraph(
            "All entered data passed validation checks.", style_normal
        ))

    # ── Footer note
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(
        "This Application Summary was generated by FormFlow — Turn complicated forms into guided applications. "
        "This document is for reference purposes only and does not constitute an official submission.",
        style_disclaimer,
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


def _generate_text_fallback(
    form_document: dict,
    values: Dict[str, Any],
    issues: List[dict],
) -> bytes:
    """Simple text fallback when ReportLab is not available."""
    lines = []
    lines.append("FORMFLOW — APPLICATION SUMMARY")
    lines.append("=" * 60)
    lines.append(f"Document: {form_document.get('title', 'Application')}")
    lines.append(f"Generated: {datetime.now().strftime('%d %B %Y %H:%M')}")
    lines.append("")

    for section in form_document.get("sections", []):
        lines.append(f"\n{section.get('title', 'Section').upper()}")
        lines.append("-" * 40)
        for field in section.get("fields", []):
            val = values.get(field.get("id", ""), "")
            lines.append(f"  {field.get('label', '')}: {val or '(not filled)'}")

    if issues:
        lines.append("\n\nVALIDATION ISSUES")
        lines.append("-" * 40)
        for issue in issues:
            lines.append(f"  [{issue.get('severity', 'info').upper()}] {issue.get('title', '')}")
            lines.append(f"  {issue.get('description', '')}")
            lines.append("")

    return "\n".join(lines).encode("utf-8")
